"""empty message

Revision ID: 6af8509cc74b
Revises: c3f8a1b2e9d4
Create Date: 2026-09-22 08:46:26.646067

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6af8509cc74b"
down_revision = "c3f8a1b2e9d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table(
        "rag_sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("message_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rag_sessions_updated_at", "rag_sessions", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_rag_sessions_user_id"), "rag_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "rag_messages",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("citations", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("model", sa.String(length=64), nullable=True),
        sa.Column("candidate_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"], ["rag_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rag_messages_session_created",
        "rag_messages",
        ["session_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rag_messages_session_created", table_name="rag_messages")
    op.drop_table("rag_messages")
    op.drop_index(op.f("ix_rag_sessions_user_id"), table_name="rag_sessions")
    op.drop_index("ix_rag_sessions_updated_at", table_name="rag_sessions")
    op.drop_table("rag_sessions")
    # ### end Alembic commands ###
