# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "tm-extractor-naxadevelopers-ap-southeast-1"
    dynamodb_table = "tm-extractor-locks"
    encrypt        = true
    key            = "./terraform.tfstate"
    region         = "ap-southeast-1"
  }
}
