# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    provider "aws" {
      region = "ap-southeast-1"

      default_tags {
        tags = {
          Environment = "DevOps"
          Application = "tasking-manager-ns"
          Team        = "NAXA-NISCHAL-DELETE-ME"
          Creator     = "NAXA-NISCHAL-DELETE-ME"
          Owner       = "NAXA-NISCHAL-DELETE-ME"
        }
      }
    }
