name: Build and Deploy Tasking Manager

on:
  push:
    branches:
      - deployment/naxa
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: [ubuntu-latest]
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Recreate Services
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SERVER_IP }}
          username: ${{ vars.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 20m
          script: |
            echo '==In Server=='
            cd /home/ubuntu/Projects/tasking-manager
            git pull naxa deployment/naxa
            docker compose build --no-cache
            docker compose up -d --force-recreate
